version: "3"

services:
    witnesshost:
        container_name: witnesshost
        hostname: witnesshost
        image: gleif/keri:latest
        tty: true
        volumes:
            - ./volume/witnesshost/keripy/scripts/keri/cf/main/:/keripy/scripts/keri/cf/main/
        ports:
            - 5642:5642  # witness
            - 5643:5643  # witness
            - 5644:5644  # witness
        entrypoint: kli witness demo

    dkr:
        container_name: dkr
        hostname: dkr
        image: gleif/dkr:latest
        tty: true
        volumes:
            - ./volume/dkr/my-scripts/:/keripy/my-scripts/
            - ./volume/dkr/did_json/:/usr/local/var/did-keri-resolver/did_json/
            - ./volume/dkr/keri_cesr/:/usr/local/var/did-keri-resolver/keri_cesr/
